name: Deploy to Firebase Hosting on Push a Commit
on: 
  push: 
    branches:
      - main
permissions: 
  checks: write
  contents: read
  pull-requests: write
jobs: 
  build_and_preview:
    if: startsWith(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: " npm i && npm run build"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTIFOLIO_LUIS_THALYS }}
          projectId: portifolio-luis-thalys